


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."code_skeletons" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "generated_code" "text" NOT NULL,
    "framework" "text" NOT NULL,
    "test_case_id" bigint
);


ALTER TABLE "public"."code_skeletons" OWNER TO "postgres";


COMMENT ON TABLE "public"."code_skeletons" IS 'Stores code skeletons for a test case.';



ALTER TABLE "public"."code_skeletons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."code_skeletons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."projects" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "user_id" "uuid" DEFAULT "auth"."uid"()
);


ALTER TABLE "public"."projects" OWNER TO "postgres";


COMMENT ON TABLE "public"."projects" IS 'Stores users'' projects.';



ALTER TABLE "public"."projects" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."projects_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."test_cases" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "type" "text",
    "precondition" "text",
    "steps" "text",
    "expected_result" "text",
    "use_case_id" bigint
);


ALTER TABLE "public"."test_cases" OWNER TO "postgres";


COMMENT ON TABLE "public"."test_cases" IS 'Stores the test cases generated by the AI.';



ALTER TABLE "public"."test_cases" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."test_cases_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."use_cases" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text",
    "actor" "text",
    "preconditions" "text",
    "main_flow" "text",
    "alternative_flows" "text",
    "description" "text",
    "project_id" bigint
);


ALTER TABLE "public"."use_cases" OWNER TO "postgres";


COMMENT ON TABLE "public"."use_cases" IS 'Stores the use cases created by users.';



ALTER TABLE "public"."use_cases" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."use_cases_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."code_skeletons"
    ADD CONSTRAINT "code_skeletons_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."projects"
    ADD CONSTRAINT "projects_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."test_cases"
    ADD CONSTRAINT "test_cases_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."use_cases"
    ADD CONSTRAINT "use_cases_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."use_cases"
    ADD CONSTRAINT "use_cases_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."code_skeletons"
    ADD CONSTRAINT "code_skeletons_test_case_id_fkey" FOREIGN KEY ("test_case_id") REFERENCES "public"."test_cases"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."projects"
    ADD CONSTRAINT "projects_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."test_cases"
    ADD CONSTRAINT "test_cases_use_case_id_fkey" FOREIGN KEY ("use_case_id") REFERENCES "public"."use_cases"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."use_cases"
    ADD CONSTRAINT "use_cases_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Allow individual delete" ON "public"."use_cases" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."projects"
  WHERE (("projects"."id" = "use_cases"."project_id") AND ("projects"."user_id" = "auth"."uid"())))));



CREATE POLICY "Allow individual delete based on parent" ON "public"."test_cases" FOR DELETE USING ((EXISTS ( SELECT 1
   FROM ("public"."use_cases" "uc"
     JOIN "public"."projects" "p" ON (("uc"."project_id" = "p"."id")))
  WHERE (("uc"."id" = "test_cases"."use_case_id") AND ("p"."user_id" = "auth"."uid"())))));



CREATE POLICY "Allow individual insert" ON "public"."use_cases" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."projects"
  WHERE (("projects"."id" = "use_cases"."project_id") AND ("projects"."user_id" = "auth"."uid"())))));



CREATE POLICY "Allow individual select" ON "public"."use_cases" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."projects"
  WHERE (("projects"."id" = "use_cases"."project_id") AND ("projects"."user_id" = "auth"."uid"())))));



CREATE POLICY "Allow individual update" ON "public"."use_cases" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."projects"
  WHERE (("projects"."id" = "use_cases"."project_id") AND ("projects"."user_id" = "auth"."uid"()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."projects"
  WHERE (("projects"."id" = "use_cases"."project_id") AND ("projects"."user_id" = "auth"."uid"())))));



CREATE POLICY "Allow individual update based on parent" ON "public"."test_cases" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM ("public"."use_cases" "uc"
     JOIN "public"."projects" "p" ON (("uc"."project_id" = "p"."id")))
  WHERE (("uc"."id" = "test_cases"."use_case_id") AND ("p"."user_id" = "auth"."uid"()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM ("public"."use_cases" "uc"
     JOIN "public"."projects" "p" ON (("uc"."project_id" = "p"."id")))
  WHERE (("uc"."id" = "test_cases"."use_case_id") AND ("p"."user_id" = "auth"."uid"())))));



CREATE POLICY "Allow insert based on parent" ON "public"."test_cases" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM ("public"."use_cases" "uc"
     JOIN "public"."projects" "p" ON (("uc"."project_id" = "p"."id")))
  WHERE (("uc"."id" = "test_cases"."use_case_id") AND ("p"."user_id" = "auth"."uid"())))));



CREATE POLICY "Allow select based on parent" ON "public"."test_cases" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM ("public"."use_cases" "uc"
     JOIN "public"."projects" "p" ON (("uc"."project_id" = "p"."id")))
  WHERE (("uc"."id" = "test_cases"."use_case_id") AND ("p"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users can manage code skeletons based on project ownership" ON "public"."code_skeletons" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM (("public"."test_cases" "tc"
     JOIN "public"."use_cases" "uc" ON (("tc"."use_case_id" = "uc"."id")))
     JOIN "public"."projects" "p" ON (("uc"."project_id" = "p"."id")))
  WHERE (("tc"."id" = "code_skeletons"."test_case_id") AND ("p"."user_id" = "auth"."uid"()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM (("public"."test_cases" "tc"
     JOIN "public"."use_cases" "uc" ON (("tc"."use_case_id" = "uc"."id")))
     JOIN "public"."projects" "p" ON (("uc"."project_id" = "p"."id")))
  WHERE (("tc"."id" = "code_skeletons"."test_case_id") AND ("p"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users can manage their own projects" ON "public"."projects" TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."code_skeletons" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."projects" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."test_cases" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."use_cases" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."code_skeletons" TO "anon";
GRANT ALL ON TABLE "public"."code_skeletons" TO "authenticated";
GRANT ALL ON TABLE "public"."code_skeletons" TO "service_role";



GRANT ALL ON SEQUENCE "public"."code_skeletons_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."code_skeletons_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."code_skeletons_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."projects" TO "anon";
GRANT ALL ON TABLE "public"."projects" TO "authenticated";
GRANT ALL ON TABLE "public"."projects" TO "service_role";



GRANT ALL ON SEQUENCE "public"."projects_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."projects_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."projects_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."test_cases" TO "anon";
GRANT ALL ON TABLE "public"."test_cases" TO "authenticated";
GRANT ALL ON TABLE "public"."test_cases" TO "service_role";



GRANT ALL ON SEQUENCE "public"."test_cases_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test_cases_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test_cases_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."use_cases" TO "anon";
GRANT ALL ON TABLE "public"."use_cases" TO "authenticated";
GRANT ALL ON TABLE "public"."use_cases" TO "service_role";



GRANT ALL ON SEQUENCE "public"."use_cases_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."use_cases_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."use_cases_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


