drop extension if exists "pg_net";


  create table "public"."test_cases" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "types" text,
    "precondition" text,
    "steps" text,
    "expected_result" text,
    "use_case_id" bigint
      );


alter table "public"."test_cases" enable row level security;


  create table "public"."use_cases" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "name" text,
    "actor" text,
    "preconditions" text,
    "main_flow" text,
    "alternative_flows" text,
    "description" text
      );


alter table "public"."use_cases" enable row level security;

CREATE UNIQUE INDEX test_cases_pkey ON public.test_cases USING btree (id);

CREATE UNIQUE INDEX use_cases_name_key ON public.use_cases USING btree (name);

CREATE UNIQUE INDEX use_cases_pkey ON public.use_cases USING btree (id);

CREATE UNIQUE INDEX use_cases_user_id_key ON public.use_cases USING btree (user_id);

alter table "public"."test_cases" add constraint "test_cases_pkey" PRIMARY KEY using index "test_cases_pkey";

alter table "public"."use_cases" add constraint "use_cases_pkey" PRIMARY KEY using index "use_cases_pkey";

alter table "public"."test_cases" add constraint "test_cases_use_case_id_fkey" FOREIGN KEY (use_case_id) REFERENCES public.use_cases(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."test_cases" validate constraint "test_cases_use_case_id_fkey";

alter table "public"."use_cases" add constraint "use_cases_name_key" UNIQUE using index "use_cases_name_key";

alter table "public"."use_cases" add constraint "use_cases_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."use_cases" validate constraint "use_cases_user_id_fkey";

alter table "public"."use_cases" add constraint "use_cases_user_id_key" UNIQUE using index "use_cases_user_id_key";

grant delete on table "public"."test_cases" to "anon";

grant insert on table "public"."test_cases" to "anon";

grant references on table "public"."test_cases" to "anon";

grant select on table "public"."test_cases" to "anon";

grant trigger on table "public"."test_cases" to "anon";

grant truncate on table "public"."test_cases" to "anon";

grant update on table "public"."test_cases" to "anon";

grant delete on table "public"."test_cases" to "authenticated";

grant insert on table "public"."test_cases" to "authenticated";

grant references on table "public"."test_cases" to "authenticated";

grant select on table "public"."test_cases" to "authenticated";

grant trigger on table "public"."test_cases" to "authenticated";

grant truncate on table "public"."test_cases" to "authenticated";

grant update on table "public"."test_cases" to "authenticated";

grant delete on table "public"."test_cases" to "service_role";

grant insert on table "public"."test_cases" to "service_role";

grant references on table "public"."test_cases" to "service_role";

grant select on table "public"."test_cases" to "service_role";

grant trigger on table "public"."test_cases" to "service_role";

grant truncate on table "public"."test_cases" to "service_role";

grant update on table "public"."test_cases" to "service_role";

grant delete on table "public"."use_cases" to "anon";

grant insert on table "public"."use_cases" to "anon";

grant references on table "public"."use_cases" to "anon";

grant select on table "public"."use_cases" to "anon";

grant trigger on table "public"."use_cases" to "anon";

grant truncate on table "public"."use_cases" to "anon";

grant update on table "public"."use_cases" to "anon";

grant delete on table "public"."use_cases" to "authenticated";

grant insert on table "public"."use_cases" to "authenticated";

grant references on table "public"."use_cases" to "authenticated";

grant select on table "public"."use_cases" to "authenticated";

grant trigger on table "public"."use_cases" to "authenticated";

grant truncate on table "public"."use_cases" to "authenticated";

grant update on table "public"."use_cases" to "authenticated";

grant delete on table "public"."use_cases" to "service_role";

grant insert on table "public"."use_cases" to "service_role";

grant references on table "public"."use_cases" to "service_role";

grant select on table "public"."use_cases" to "service_role";

grant trigger on table "public"."use_cases" to "service_role";

grant truncate on table "public"."use_cases" to "service_role";

grant update on table "public"."use_cases" to "service_role";


  create policy "Allow individual delete based on parent"
  on "public"."test_cases"
  as permissive
  for delete
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.use_cases uc
  WHERE ((uc.id = test_cases.use_case_id) AND (uc.user_id = auth.uid())))));



  create policy "Allow individual update based on parent"
  on "public"."test_cases"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.use_cases uc
  WHERE ((uc.id = test_cases.use_case_id) AND (uc.user_id = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM public.use_cases uc
  WHERE ((uc.id = test_cases.use_case_id) AND (uc.user_id = auth.uid())))));



  create policy "Allow insert based on parent"
  on "public"."test_cases"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.use_cases
  WHERE ((use_cases.id = test_cases.use_case_id) AND (use_cases.user_id = auth.uid())))));



  create policy "Allow select based on parent"
  on "public"."test_cases"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.use_cases
  WHERE ((use_cases.id = test_cases.use_case_id) AND (use_cases.user_id = auth.uid())))));



  create policy "Allow individual delete"
  on "public"."use_cases"
  as permissive
  for delete
  to authenticated
using ((auth.uid() = user_id));



  create policy "Allow individual insert"
  on "public"."use_cases"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "Allow individual select"
  on "public"."use_cases"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "Allow individual update"
  on "public"."use_cases"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



